# -*- coding: utf-8 -*-
"""drop 1 deform_final'25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13YMnXXYfoNswGMWUsWVHoxjpZq0bjFAD

<a href="https://colab.research.google.com/github/nadiajelani/football_analytics/blob/main/deform_final'25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

# Install OpenCV if not already installed
!pip install opencv-python-headless

# Import libraries
import cv2
import numpy as np
import os
from google.colab import drive  # Import drive to mount Google Drive
# Mount Google Drive
drive.mount('/content/drive')

image_folder = '/content/drive/MyDrive/Data and Videos/Ball 1/Drop 1'

# List to store image file names (assuming sequential names like frame1.bmp, frame2.bmp, etc.)
image_files = sorted([os.path.join(image_folder, f) for f in os.listdir(image_folder) if f.endswith('.bmp')])
if not image_files:
    raise ValueError(f"No .bmp files found in {image_folder}. Please check the folder path and ensure .bmp files exist.")

# Read the first image to initialize
frame = cv2.imread(image_files[0], cv2.IMREAD_GRAYSCALE)
if frame is None:
    raise ValueError(f"Failed to load the first image: {image_files[0]}")

# Preprocess the first frame
_, thresh = cv2.threshold(frame, 50, 255, cv2.THRESH_BINARY_INV)

# Find contours to get initial object position
contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
if contours:
    largest_contour = max(contours, key=cv2.contourArea)
    M = cv2.moments(largest_contour)
    if M["m00"] != 0:
        cx = int(M["m10"] / M["m00"])
        cy = int(M["m01"] / M["m00"])
    else:
        cx, cy = frame.shape[1] // 2, frame.shape[0] // 2  # Default center if no contour
else:
    cx, cy = frame.shape[1] // 2, frame.shape[0] // 2

# Initialize Kalman Filter (4 states: x, y, dx, dy; 2 measurements: x, y)
kalman = cv2.KalmanFilter(4, 2)
kalman.measurementMatrix = np.array([[1, 0, 0, 0], [0, 1, 0, 0]], np.float32)
kalman.transitionMatrix = np.array([[1, 0, 1, 0], [0, 1, 0, 1], [0, 0, 1, 0], [0, 0, 0, 1]], np.float32)
kalman.processNoiseCov = np.eye(4, dtype=np.float32) * 0.03
kalman.statePre = np.array([[cx], [cy], [0], [0]], np.float32)  # Initial state

# Apply Canny edge detection to find the surface line
edges = cv2.Canny(frame, 50, 150, apertureSize=3)

# Use Hough Transform to detect lines
lines = cv2.HoughLinesP(edges, 1, np.pi / 180, threshold=100, minLineLength=100, maxLineGap=10)

# Find the horizontal line closest to the bottom (assuming it's the surface)
surface_y = frame.shape[0]  # Default to bottom if no line is found
if lines is not None:
    for line in lines:
        x1, y1, x2, y2 = line[0]
        if abs(y1 - y2) < 10:  # Horizontal line (small y difference)
            surface_y = min(y1, y2)  # Take the lowest y as the surface
            break

print(f"Detected surface at y = {surface_y}")

import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import cv2
from google.colab.patches import cv2_imshow

# Define image folder and load image files
image_folder = '/content/drive/MyDrive/Data and Videos/Ball 1/Drop 1'
image_files = sorted([os.path.join(image_folder, f) for f in os.listdir(image_folder) if f.endswith('.bmp')])
if not image_files:
    raise ValueError(f"No .bmp files found in {image_folder}. Please check the folder path and ensure .bmp files exist.")

# Read the first image to initialize
frame = cv2.imread(image_files[0], cv2.IMREAD_GRAYSCALE)
if frame is None:
    raise ValueError(f"Failed to load the first image: {image_files[0]}")

# Detect surface line using Hough Transform
edges = cv2.Canny(frame, 50, 150, apertureSize=3)
lines = cv2.HoughLinesP(edges, 1, np.pi / 180, threshold=100, minLineLength=100, maxLineGap=10)
surface_y = frame.shape[0]  # Default to bottom if no line is found
if lines is not None:
    for line in lines:
        x1, y1, x2, y2 = line[0]
        if abs(y1 - y2) < 10:  # Horizontal line (small y difference)
            surface_y = min(y1, y2)  # Take the lowest detected horizontal line

print(f"Detected surface at y = {surface_y}")

# Kalman Filter Setup for Stable Circle Detection
kalman = cv2.KalmanFilter(4, 2)
kalman.measurementMatrix = np.array([[1, 0, 0, 0], [0, 1, 0, 0]], np.float32)
kalman.transitionMatrix = np.array([[1, 0, 1, 0], [0, 1, 0, 1], [0, 0, 1, 0], [0, 0, 0, 1]], np.float32)
kalman.processNoiseCov = np.eye(4, dtype=np.float32) * 0.02  # Increased smoothness
# Initialize Kalman Filter state with default values (will be updated with first detection)
kalman.statePre = np.array([[frame.shape[1] // 2], [frame.shape[0] // 2], [0], [0]], np.float32)

# Initialize Variables
D_original = None
last_valid_radius = None
last_valid_contact_points = None  # To track previous frame's contact points
data_records = []
dot_records = []  # To store dot positions

# Process frames 1450 to 1650
start_frame = 1450
end_frame = 1650
for i, img_file in enumerate(image_files):
    if i < start_frame or i >= end_frame:
        continue

    # Read and preprocess current frame
    frame = cv2.imread(img_file, cv2.IMREAD_GRAYSCALE)
    if frame is None:
        print(f"Failed to load {img_file}")
        continue

    # Apply Gaussian blur and thresholding
    blurred = cv2.GaussianBlur(frame, (5, 5), 0)
    thresh = cv2.adaptiveThreshold(blurred, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 11, 2)

    # Detect circle using Hough Transform
    circles = cv2.HoughCircles(frame, cv2.HOUGH_GRADIENT, dp=1.2, minDist=50, param1=50, param2=30, minRadius=20, maxRadius=100)

    # Predict using Kalman Filter
    prediction = kalman.predict()
    predicted_cx, predicted_cy = int(prediction[0]), int(prediction[1])

    cx, cy, radius = None, None, None
    if circles is not None:
        circles = np.uint16(np.around(circles))
        for circle in circles[0, :]:
            cx, cy, radius = circle  # Extract circle center and radius
            break  # Only take the first detected circle

        # Stabilize circle detection using Kalman Filter
        if last_valid_radius is not None:
            radius = int(0.85 * last_valid_radius + 0.15 * radius)  # Smooth transition
        last_valid_radius = radius  # Update last valid radius
        kalman.correct(np.array([[np.float32(cx)], [np.float32(cy)]]))
    else:
        # Use predicted values if no circle is detected
        cx, cy = predicted_cx, predicted_cy
        radius = last_valid_radius if last_valid_radius is not None else 50  # Fallback radius

    # Convert frame to color for drawing
    frame_color = cv2.cvtColor(frame, cv2.COLOR_GRAY2BGR)

    # Initialize dot positions as None
    top_dot_x, top_dot_y = None, None
    bottom_dot_x, bottom_dot_y = None, None
    contact_dot1_x, contact_dot1_y = None, None
    contact_dot2_x, contact_dot2_y = None, None
    diameter = 0
    contact_length = 0

    if radius is not None:
        # Define Top and Bottom Points
        top_point = (cx, cy - int(radius))
        bottom_point = (cx, cy + int(radius))

        # Ensure bottom point does not go below surface_y
        if bottom_point[1] >= surface_y:
            bottom_point = (cx, surface_y)

        # Store Top and Bottom Dot positions
        top_dot_x, top_dot_y = top_point
        bottom_dot_x, bottom_dot_y = bottom_point

        # Compute Diameter
        diameter = bottom_point[1] - top_point[1]
        diameter = max(diameter, 20)  # Avoid unrealistic values
        print(f"Frame {i + 1}: Diameter = {diameter} pixels")

        # Store initial diameter before deformation
        if D_original is None and bottom_point[1] < surface_y - 50:
            D_original = diameter
            print(f"Frame {i + 1}: D_original set to {D_original} pixels")

        # Draw Stable Blue Circle
        cv2.circle(frame_color, (cx, cy), int(radius), (255, 0, 0), 1)

        # Detect Contact Points (Yellow Dots)
        contact_point1 = None
        contact_point2 = None
        if bottom_point[1] == surface_y:  # When ball is in contact
            delta_y = surface_y - cy
            discriminant = radius**2 - delta_y**2
            if discriminant >= 0:
                sqrt_disc = np.sqrt(discriminant)
                x1 = int(cx - sqrt_disc)
                x2 = int(cx + sqrt_disc)
                contact_point1 = (x1, surface_y)
                contact_point2 = (x2, surface_y)
                contact_length = x2 - x1
                print(f"Contact detected! Contact Length: {contact_length} pixels")

                # Validate new contact points
                if last_valid_contact_points is not None:
                    x1_prev, x2_prev = last_valid_contact_points
                    if abs(x1 - x1_prev) > 10 or abs(x2 - x2_prev) > 10:
                        x1, x2 = x1_prev, x2_prev  # Use previous frame's values if new ones are unstable

                last_valid_contact_points = (x1, x2)  # Update valid points

                # Store Contact Dot positions
                contact_dot1_x, contact_dot1_y = contact_point1
                contact_dot2_x, contact_dot2_y = contact_point2

                # Draw Contact Dots in Yellow
                cv2.circle(frame_color, contact_point1, 3, (0, 255, 255), -1)
                cv2.circle(frame_color, contact_point2, 3, (0, 255, 255), -1)

    # Draw Surface Line (Green)
    cv2.line(frame_color, (0, surface_y), (frame.shape[1], surface_y), (0, 255, 0), 1)

    # Draw Top & Bottom Dots for Diameter (Cyan)
    if top_point is not None and bottom_point is not None:
        cv2.circle(frame_color, top_point, 3, (255, 255, 0), -1)
        cv2.circle(frame_color, bottom_point, 3, (255, 255, 0), -1)

    # Save Data for Original CSV (Diameter and Contact Length)
    data_records.append([i + 1, cx, cy, diameter, contact_length])

    # Save Dot Positions for New CSV
    dot_records.append([i + 1, top_dot_x, top_dot_y, bottom_dot_x, bottom_dot_y,
                        contact_dot1_x, contact_dot1_y, contact_dot2_x, contact_dot2_y])

    # Display Frame
    cv2_imshow(frame_color)
    if cv2.waitKey(30) & 0xFF == ord('q'):
        break
2
cv2.destroyAllWindows()

"""CSV"""

# Save Data to CSV
df = pd.DataFrame(data_records, columns=["Frame", "Ball_X", "Ball_Y", "Diameter", "Contact_Length"])
df.to_csv("/content/drive/MyDrive/Colab Notebooks/Football_CSV/Drop1.csv", index=False)

# Create New CSV for Dot Positions
dot_df = pd.DataFrame(dot_records, columns=["Frame",
                                            "Top_Dot_X", "Top_Dot_Y",
                                            "Bottom_Dot_X", "Bottom_Dot_Y",
                                            "Contact_Dot1_X", "Contact_Dot1_Y",
                                            "Contact_Dot2_X", "Contact_Dot2_Y"])
dot_df.to_csv("/content/drive/MyDrive/Colab Notebooks/Football_CSV/Drop1_positions.csv", index=False)


# Display the Dot Positions Table (First 10 Frames)
print("\nTable of Dot Positions (First 10 Frames):")
print(dot_df.head(10))

"""MIN VS MAX"""

import pandas as pd

# Load the CSV file
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Football_CSV/Drops/Drop1.csv")  # Replace with your actual filename


# Calculate Contact Length stats
max_contact = df["Contact_Length"].max()
min_contact = df["Contact_Length"].min()

# Calculate Diameter stats
max_diameter = df["Diameter"].max()
min_diameter = df["Diameter"].min()

# Display the results
print(f"Max Contact Length: {max_contact} pixels")
print(f"Min Contact Length: {min_contact} pixels")
print(f"Max Diameter: {max_diameter} pixels")
print(f"Min Diameter: {min_diameter} pixels")

"""GRAPHS"""

import pandas as pd

import matplotlib.pyplot as plt

import glob

import os

# Path to CSV files

csv_files = glob.glob("/content/drive/MyDrive/Colab Notebooks/Football_CSV/Drops/*.csv")  # Update path

# Plot Contact Length and Diameter

plt.figure(figsize=(12, 6))

for file in csv_files:

    df = pd.read_csv(file)

    label = os.path.basename(file).replace(".csv", "")

    # Filter out contact length <= 0 if needed

    df = df[df["Contact_Length"] > 0]

    # Plot contact length

    plt.plot(df["Frame"], df["Contact_Length"], label=f"{label} - Contact_lenght", linestyle='--')

    # Plot diameter (optional, on same graph)

 #   plt.plot(df["Frame"], df["Diameter"], label=f"{label} - Diameter")

plt.xlabel("Frame Number")

plt.ylabel("Pixels")

plt.title("Contact Length Over Time (Multiple CSVs)")

plt.legend()

plt.grid(True)

plt.tight_layout()

plt.savefig("multi_csv_comparison.png")

plt.show()

"""DIAMETER"""

import pandas as pd

import matplotlib.pyplot as plt

import glob

import os

# Path to CSV files

csv_files = glob.glob("/content/drive/MyDrive/Colab Notebooks/Football_CSV/Drops/*.csv")  # Update path

# Plot Contact Length and Diameter

plt.figure(figsize=(12, 6))

for file in csv_files:

    df = pd.read_csv(file)

    label = os.path.basename(file).replace(".csv", "")

    # Filter out contact length <= 0 if needed

    #df = df[df["Contact_Length"] > 0]

    # Plot contact length

    #plt.plot(df["Frame"], df["Contact_Length"], label=f"{label} - Contact_lenght", linestyle='--')

    # Plot diameter (optional, on same graph)

    plt.plot(df["Frame"], df["Diameter"], label=f"{label} - Diameter")

plt.xlabel("Frame Number")

plt.ylabel("Pixels")

plt.title("Daimeter Over Time (Multiple CSVs)")

plt.legend()

plt.grid(True)

plt.tight_layout()

plt.savefig("multi_csv_comparison.png")

plt.show()

"""SMOOTH"""

import pandas as pd

import matplotlib.pyplot as plt

from scipy.signal import savgol_filter

import glob

import os

# Path to CSV files

csv_files = glob.glob("/content/drive/MyDrive/Colab Notebooks/Football_CSV/Drops/*.csv")  # 🔁 Replace with your path

# Start figure

plt.figure(figsize=(14, 7))

# Loop through each CSV

for file in csv_files:

    df = pd.read_csv(file)

    label = os.path.basename(file).replace(".csv", "")

    # Filter out contact length = 0

    df = df[df["Contact_Length"] > 0]

    # Ensure enough points for smoothing

    if len(df) < 7:

        continue  # Skip files with too few points

    # Determine proper window length

    window = 11 if len(df) >= 11 else len(df) // 2 * 2 + 1

    poly = 3 if window >= 5 else 2

    # Apply smoothing

    df["Contact_Smooth"] = savgol_filter(df["Contact_Length"], window_length=window, polyorder=poly)

    df["Diameter_Smooth"] = savgol_filter(df["Diameter"], window_length=window, polyorder=poly)

    # Plot smoothed values

    plt.plot(df["Frame"], df["Contact_Smooth"], linestyle='--', label=f"{label} - Contact")

    #plt.plot(df["Frame"], df["Diameter_Smooth"], linestyle='-', label=f"{label} - Diameter")

# Final touches

plt.xlabel("Frame Number")

plt.ylabel("Pixels")

plt.title("Smoothed Contact Length Over Time")

plt.legend()

plt.grid(True)

plt.tight_layout()

plt.savefig("smoothed_multi_csv_comparison.png")

plt.show()

import pandas as pd

import matplotlib.pyplot as plt

from scipy.signal import savgol_filter

import glob

import os

# Path to CSV files

csv_files = glob.glob("/content/drive/MyDrive/Colab Notebooks/Football_CSV/Drops/*.csv")  # 🔁 Replace with your path

# Start figure

plt.figure(figsize=(14, 7))

# Loop through each CSV

for file in csv_files:

    df = pd.read_csv(file)

    label = os.path.basename(file).replace(".csv", "")

    # Filter out contact length = 0

    df = df[df["Contact_Length"] > 0]

    # Ensure enough points for smoothing

    if len(df) < 7:

        continue  # Skip files with too few points

    # Determine proper window length

    window = 11 if len(df) >= 11 else len(df) // 2 * 2 + 1

    poly = 3 if window >= 5 else 2

    # Apply smoothing

    df["Contact_Smooth"] = savgol_filter(df["Contact_Length"], window_length=window, polyorder=poly)

    df["Diameter_Smooth"] = savgol_filter(df["Diameter"], window_length=window, polyorder=poly)

    # Plot smoothed values

    #plt.plot(df["Frame"], df["Contact_Smooth"], linestyle='--', label=f"{label} - Contact")

    plt.plot(df["Frame"], df["Diameter_Smooth"], linestyle='-', label=f"{label} - Diameter")

# Final touches

plt.xlabel("Frame Number")

plt.ylabel("Pixels")

plt.title("Smoothed Diameter Over Time")

plt.legend()

plt.grid(True)

plt.tight_layout()

plt.savefig("smoothed_multi_csv_comparison.png")

plt.show()

"""INBOUND VELOCITY , OUTBOUND VELOCITY AND COR"""

import matplotlib.pyplot as plt

# Time interval based on 10,000 frames per second
frame_rate = 10000
time_interval = 1 / frame_rate
pixels_to_meters = 0.00128  # 172 pixels ≈ 0.22 m

# Calculate time column
df["Time_s"] = (df["Frame"] - df["Frame"].min()) / frame_rate

# Inbound velocity (Vi) using frames 1534 and 1535
y_1534 = df.loc[df["Frame"] == 1534, "Ball_Y"].values[0]
y_1535 = df.loc[df["Frame"] == 1535, "Ball_Y"].values[0]
vi_pixels = (y_1535 - y_1534) / time_interval
vi_mps = vi_pixels * pixels_to_meters

# Outbound velocity (V0) using frames 1640 and 1641
y_1640 = df.loc[df["Frame"] == 1640, "Ball_Y"].values[0]
y_1641 = df.loc[df["Frame"] == 1641, "Ball_Y"].values[0]
v0_pixels = (y_1641 - y_1640) / time_interval
v0_mps = v0_pixels * pixels_to_meters

# COR calculation
cor = abs(v0_mps) / abs(vi_mps)

# Plotting Ball_Y over time
plt.figure(figsize=(12, 6))
plt.plot(df["Time_s"], df["Ball_Y"], label="Ball Center Y", color='blue')
plt.axvline(x=(1536 - df["Frame"].min()) / frame_rate, color='green', linestyle='--', label='Touches Ground (Frame 1536)')
plt.axvline(x=(1640 - df["Frame"].min()) / frame_rate, color='red', linestyle='--', label='Leaves Surface (Frame 1640)')
plt.xlabel("Time (seconds)")
plt.ylabel("Ball_Y (pixels)")
plt.title("Ball Y Position Over Time")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

vi_mps, v0_mps, cor

import matplotlib.pyplot as plt

# Plotting Ball_Y over time

plt.figure(figsize=(12, 6))

plt.plot(df["Time_s"], df["Ball_Y"], label="Ball Center Y", color='blue')

# Vertical lines for ground contact

plt.axvline(x=(1536 - df["Frame"].min()) / frame_rate, color='green', linestyle='--', label='Touches Ground (Frame 1536)')

plt.axvline(x=(1640 - df["Frame"].min()) / frame_rate, color='red', linestyle='--', label='Leaves Surface (Frame 1640)')

# Add arrows for inbound and outbound velocities

inbound_x = (1535 - df["Frame"].min()) / frame_rate

outbound_x = (1640 - df["Frame"].min()) / frame_rate

# Inbound arrow

plt.annotate(

    'Inbound Velocity\nVi = {:.2f} m/s'.format(vi_mps),

    xy=(inbound_x, y_1535),

    xytext=(inbound_x - 0.0015, y_1535 + 10),

    arrowprops=dict(facecolor='blue', shrink=0.05, width=2, headwidth=8),

    fontsize=10,

    color='blue',

    ha='right'

)

# Outbound arrow

plt.annotate(

    'Outbound Velocity\nV₀ = {:.2f} m/s'.format(v0_mps),

    xy=(outbound_x, y_1640),

    xytext=(outbound_x + 0.0015, y_1640 - 20),

    arrowprops=dict(facecolor='green', shrink=0.05, width=2, headwidth=8),

    fontsize=10,

    color='green',

    ha='left'

)

# Final touches

plt.xlabel("Time (seconds)")

plt.ylabel("Ball_Y (pixels)")

plt.title("Ball Y Position with Inbound and Outbound Velocities")

plt.legend()

plt.grid(True)

plt.tight_layout()

plt.show()

from scipy.signal import savgol_filter

# Apply Savitzky-Golay filter to smooth the Ball_Y data

df["Ball_Y_Smooth"] = savgol_filter(df["Ball_Y"], window_length=11, polyorder=3)

# Plotting Smoothed Ball_Y over time

plt.figure(figsize=(12, 6))

plt.plot(df["Time_s"], df["Ball_Y_Smooth"], label="Smoothed Ball Center Y", color='blue')

# Vertical lines for ground contact

plt.axvline(x=(1536 - df["Frame"].min()) / frame_rate, color='green', linestyle='--', label='Touches Ground (Frame 1536)')

plt.axvline(x=(1640 - df["Frame"].min()) / frame_rate, color='red', linestyle='--', label='Leaves Surface (Frame 1640)')

# Inbound arrow

plt.annotate(

    'Inbound Velocity\nVi = {:.2f} m/s'.format(vi_mps),

    xy=((1535 - df["Frame"].min()) / frame_rate, y_1535),

    xytext=((1535 - df["Frame"].min()) / frame_rate - 0.0015, y_1535 + 10),

    arrowprops=dict(facecolor='blue', shrink=0.05, width=2, headwidth=8),

    fontsize=10,

    color='blue',

    ha='right'

)

# Outbound arrow

plt.annotate(

    'Outbound Velocity\nV₀ = {:.2f} m/s'.format(v0_mps),

    xy=((1640 - df["Frame"].min()) / frame_rate, y_1640),

    xytext=((1640 - df["Frame"].min()) / frame_rate + 0.0015, y_1640 - 20),

    arrowprops=dict(facecolor='green', shrink=0.05, width=2, headwidth=8),

    fontsize=10,

    color='green',

    ha='left'

)

# Final touches

plt.xlabel("Time (seconds)")

plt.ylabel("Ball_Y (pixels)")

plt.title("Smoothed Ball Y Position with Inbound and Outbound Velocities")

plt.legend()

plt.grid(True)

plt.tight_layout()

plt.show()
